spring:
  application:
    name: "food-service"

#DB Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/food_db
    username: foodieMicro
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# JPA and Hibernate Configuration in Properties file;
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

#eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
#to enable info env
  info:
    env:
      enabled: true
